### ISSUE TITLE
Update POM

### ISSUE THREAD

**Issue by Anzo52** [Anzo52/JavaCryptoBot#1]
Dependencies in POM.xml need to be updated.

**Comment by vishalsingh2972** [comment]
@Anzo52 can you assign this to me if it's open. Also, could you briefly tell me what is the issue that you're currently facing so that I can get more clarity on which dependencies to add and which to remove if any?

**Comment by vishalsingh2972** [comment]
Done @Anzo52  could you please check PR https://github.com/Anzo52/JavaCryptoBot/pull/2 and merge it

**Comment by vishalsingh2972** [comment]
@Anzo52 could you check and merge PR https://github.com/Anzo52/JavaCryptoBot/pull/3

**Comment by vishalsingh2972** [comment]
@Anzo52 could you check and merge PR https://github.com/Anzo52/JavaCryptoBot/pull/3

**Comment by vishalsingh2972** [comment]
@Anzo52 could you check and merge PR https://github.com/Anzo52/JavaCryptoBot/pull/3
